# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - stream-central-fetch

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.11' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: get .env files
        run: |
          cd azure_functions
          echo ${{ secrets.ENV_FILE }} | base64 -d > FetchMovies/.env
          echo ${{ secrets.ENV_FILE }} | base64 -d > FetchTVShows/.env

      - name: Create and start virtual environment
        run: |
          cd azure_functions
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          cd azure_functions
          pwd
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd azure_functions
          pwd
          zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            azure_functions/release.zip
            !azure_functions/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip     
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6D3E315ECBF24907A0A37F89CD156F7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5E7EC806FAAC4A3D9D41B42419EA629D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EC2C4C84BC2C4CE9B14946039DCF4E74 }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'stream-central-fetch'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          
